/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;

/**
 *
 * @author kali
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form DashBorad
     */
    Color panDefualt,panEnter,panClick;
    public Signup() {
        initComponents();
        setLocationRelativeTo(null);
        panDefualt = new Color(240,151,57);
        panClick = new Color(243,183,68);
        panEnter = new Color(243,98,43);
        
        Sign.setBackground(panDefualt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldSignup = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldSignup1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldSignup2 = new javax.swing.JTextField();
        Sign = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 550));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(13, 39, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(240, 151, 47));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 65)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SIGNUP");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 250, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/signup.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 110, 120));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 550));

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 100, 40));

        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 260, -1));

        jTextFieldSignup.setBackground(new java.awt.Color(13, 39, 51));
        jTextFieldSignup.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jTextFieldSignup.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldSignup.setBorder(null);
        jTextFieldSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldSignupMouseEntered(evt);
            }
        });
        jTextFieldSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSignupActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 260, 30));

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 100, 40));

        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 260, -1));

        jTextFieldSignup1.setBackground(new java.awt.Color(13, 39, 51));
        jTextFieldSignup1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jTextFieldSignup1.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldSignup1.setBorder(null);
        jTextFieldSignup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldSignup1MouseEntered(evt);
            }
        });
        jTextFieldSignup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSignup1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldSignup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 260, 30));

        jLabel8.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 100, 40));

        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 260, -1));

        jTextFieldSignup2.setBackground(new java.awt.Color(13, 39, 51));
        jTextFieldSignup2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jTextFieldSignup2.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldSignup2.setBorder(null);
        jTextFieldSignup2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldSignup2MouseEntered(evt);
            }
        });
        jTextFieldSignup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSignup2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldSignup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 260, 30));

        Sign.setBackground(new java.awt.Color(240, 151, 47));
        Sign.setToolTipText("");
        Sign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SignMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SignMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SIGNUP");

        javax.swing.GroupLayout SignLayout = new javax.swing.GroupLayout(Sign);
        Sign.setLayout(SignLayout);
        SignLayout.setHorizontalGroup(
            SignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        SignLayout.setVerticalGroup(
            SignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(Sign, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 270, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSignupMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSignupMouseEntered

    private void jTextFieldSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSignupActionPerformed

    private void jTextFieldSignup1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSignup1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSignup1MouseEntered

    private void jTextFieldSignup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSignup1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSignup1ActionPerformed

    private void jTextFieldSignup2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSignup2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSignup2MouseEntered

    private void jTextFieldSignup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSignup2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSignup2ActionPerformed

    private void SignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignMouseClicked
        // TODO add your handling code here:
        Sign.setBackground(panDefualt);
    }//GEN-LAST:event_SignMouseClicked

    private void SignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignMouseEntered
        // TODO add your handling code here:
        Sign.setBackground(panEnter);
    }//GEN-LAST:event_SignMouseEntered

    private void SignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignMouseExited
        // TODO add your handling code here:
        Sign.setBackground(panDefualt);
    }//GEN-LAST:event_SignMouseExited

    private void SignMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignMousePressed
        // TODO add your handling code here:
        Sign.setBackground(panDefualt);
    }//GEN-LAST:event_SignMousePressed

    private void SignMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignMouseReleased
        // TODO add your handling code here:
        Sign.setBackground(panDefualt);
    }//GEN-LAST:event_SignMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Sign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldSignup;
    private javax.swing.JTextField jTextFieldSignup1;
    private javax.swing.JTextField jTextFieldSignup2;
    // End of variables declaration//GEN-END:variables
}
